package com.nn.application.service;

import com.nn.domain.dto.AccountDto;
import com.nn.domain.dto.CreateAccountRequest;
import com.nn.domain.model.Account;

import java.math.BigDecimal;

public class AccountMapper {
    public static AccountDto toDto(Account account) {
        AccountDto dto = new AccountDto();
        dto.setId(account.getId());
        dto.setFirstName(account.getFirstName());
        dto.setLastName(account.getLastName());
        dto.setBalancePln(account.getBalancePln());
        dto.setBalanceUsd(account.getBalanceUsd());
        return dto;
    }

    public static Account toEntity(CreateAccountRequest request) {
        return new Account(null,//ID will be generated by database
                request.getFirstName(),
                request.getLastName(),
                request.getBalancePln(),
                BigDecimal.ZERO
        );
    }
}
